name: Build and Test Workflow
on:
  push:
    branches:
      - v2.x/staging 
      - v2.x/master
      - v2.x/rc 
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      PERFORM_RELEASE:
        description: '[Release] perform release'
        required: false
        default: 'false'
  

jobs:
  check-permission:
    runs-on: ubuntu-latest
    steps:
      # this action will fail the whole workflow if permission check fails
      - name: check permission
        uses: zowe-actions/shared-actions/permission-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    runs-on: ubuntu-latest
    needs: check-permission
    steps: 
      - name: '[Prep 1] Checkout'
        uses: actions/checkout@v2

      - name: '[Prep 2] Setup jFrog CLI'
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: '[Prep 3] Set date'
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: '[Prep 4] Set version'
        id: version
        run: echo "::set-output name=version::$(cat build/configmgr_version.txt)"
      
      - name: '[Prep 3] Prepare workflow'
        uses: zowe-actions/shared-actions/prepare-workflow@main

      - name: '[Packaging] Make pax'
        uses: zowe-actions/shared-actions/make-pax@main
        with:
          pax-name: 'configmgr'
          pax-options: '-x os390 -pp'
          pax-local-workspace: './.pax/configmgr'
          pax-ssh-username: ${{ secrets.SSH_MARIST_USERNAME }}
          pax-ssh-password: ${{ secrets.SSH_MARIST_RACF_PASSWORD }}

      - name: '[Publish] Publish'
        uses: zowe-actions/shared-actions/publish@main
        if: success()
        with:
          artifacts: |
            .pax/configmgr/configmgr.pax
          publish-target-path-pattern: configmgr/${{ steps.version.output.version }}-${{ CURRENT_BRANCH }}-${{ github.run_number }}-${{ steps.date.output.date }}
          perform-release: ${{ github.event.inputs.PERFORM_RELEASE }}
 
